apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  POSTGRES_HOST: {{ .Values.postgres.host}}
  POSTGRES_PORT: {{ .Values.postgres.port }}
  POSTGRES_DB: {{ .Values.postgres.db }}
	POSTGRES_USER: {{ .Values.postgres.user }}
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
