apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: django
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
            - secretRef: 
                name: {{ .Release.Name }}-secret
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "500m"


          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom: 
                secretKeyRef:
                  name: djangoapp-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: djangoapp-secret
                  key: mongo-root-password