apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: "{{ .Values.service.type }}"
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}   # should be 80 ?
      targetPort: {{ .Values.service.targetPort }} # should be 8000 